version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 7.0.7
    - 7.1.0
    - 7.2.1
    - 7.2.3
    - 7.3.4
  registries:
  - npm-registry-npm-pkg-github-com
